version: "3.9"

services:
  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - xarvis
    user: "1000:1000"


  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres-n8n
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_N8N_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_N8N_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_N8N_PASSWORD}
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=${N8N_PORT}
    depends_on:
      - postgres-n8n
    volumes:
      - ./n8n:/home/node/.n8n
    networks:
      - xarvis
    user: "1000:1000"


  postgres-n8n:
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_N8N_USER}
      POSTGRES_PASSWORD: ${POSTGRES_N8N_PASSWORD}
      POSTGRES_DB: ${POSTGRES_N8N_DB}
    volumes:
      - pgdata-n8n:/var/lib/postgresql/data
    networks:
      - xarvis

  postgres-xarvis-core:
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_XARVIS_USER}
      POSTGRES_PASSWORD: ${POSTGRES_XARVIS_PASSWORD}
      POSTGRES_DB: ${POSTGRES_XARVIS_DB}
    volumes:
      - pgdata-xarvis-core:/var/lib/postgresql/data
    networks:
      - xarvis

  xarvis-core:
    image: ghcr.io/mdalvarenga/xarvis-mark-i/xarvis:latest
    ports:
      - "8080:8080"
    networks:
      - xarvis
    depends_on:
      - postgres-xarvis-core

volumes:
  caddy_data:
  caddy_config:
  pgdata-n8n:
  pgdata-xarvis-core:

networks:
  xarvis:
    driver: bridge
