name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy app on VPS
        run: |
          echo "Configurando SSH"
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          echo "Desactivando verificación de host para CI"
          echo "Host vps
          HostName ${{ secrets.SSH_HOST }}
          User ${{ secrets.SSH_USER }}
          IdentityFile ~/.ssh/id_ed25519
          StrictHostKeyChecking no
          UserKnownHostsFile=/dev/null
          " > ~/.ssh/config

          echo "Generando .env localmente"
          cat > .env <<EOL
          POSTGRES_N8N_USER=${{ secrets.POSTGRES_N8N_USER }}
          POSTGRES_N8N_PASSWORD=${{ secrets.POSTGRES_N8N_PASSWORD }}
          POSTGRES_N8N_DB=${{ secrets.POSTGRES_N8N_DB }}
          POSTGRES_XARVIS_USER=${{ secrets.POSTGRES_XARVIS_USER }}
          POSTGRES_XARVIS_PASSWORD=${{ secrets.POSTGRES_XARVIS_PASSWORD }}
          POSTGRES_XARVIS_DB=${{ secrets.POSTGRES_XARVIS_DB }}
          N8N_BASIC_AUTH_USER=${{ secrets.N8N_BASIC_AUTH_USER }}
          N8N_BASIC_AUTH_PASSWORD=${{ secrets.N8N_BASIC_AUTH_PASSWORD }}
          N8N_HOST=agente.markverse.io
          N8N_PORT=5678
          EOL

          echo "Subiendo .env al servidor"
          scp -i ~/.ssh/id_ed25519 .env vps:/home/github-actions/markverse/infra/.env

          echo "Ejecutando deploy remoto"
          ssh vps << 'EOF'
            cd /home/github-actions/markverse/infra

            echo "Ajustando permisos para volúmenes"
            mkdir -p ./n8n
            chown -R 1000:1000 ./n8n

            echo "Pull del repo y despliegue"
            git pull origin main
            docker compose pull
            docker compose up -d --remove-orphans
          EOF
